### ISSUE TITLE
Handle cases where "errors" in weighting cause undesirable results

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/SS-WeightingServices#2]
Per Pete, sometimes the values in the functions cause "errors" in weighting that were determined to be unreliable. We need to handle these cases appropriately.

These lines: [L83-84](https://github.com/USGS-WiM/SS-WeightingServices/blob/master/ChannelWidthWeighting.py#L83L84) and [L118-119](https://github.com/USGS-WiM/SS-WeightingServices/blob/master/ChannelWidthWeighting.py#L118L119) give warnings about issues where the input estimates are highly correlated. When this happens, we need to give a warning in the service response.

Example sets of values that causes this issue:

weightest3:
```
{
  "x1": 2.74,
  "x2": 2.45,
  "x3": 2.50,
  "sep1": 0.234,
  "sep2": 0.262,
  "sep3": 0.283,
  "r12": 0.553,
  "r13": 0.518,
  "r23": 0.907
}
```
Output: Z = 2.632, SEPZ = 0.2166

weightest2:
```
{
  "x1": 1.607,
  "x2": 1.802,
  "sep1": 0.554,
  "sep2": 0.677,
  "r12": 0.658
}
```
Output: Z = 165, SEPZ = 0.543

**Comment by amedenblik** [comment]
Set of values that will cause this issue after #1 is closed:

```
{
  "x1": 63,
  "x2": 40.8,
  "x3": 131,
  "sep1": 0.06766,
  "sep2": 0.05533,
  "sep3": 0.03923,
  "regressionRegionCode": "GC1841",
  "code1": "PK66_7AEP",
  "code2": "RSPK66_7AEP",
  "code3": "ACPK66_7AEP"
}
```

**Comment by harper-wavra** [comment]
It seems like the warning is not coming back with the request, we should check if it is actually working or not.
